/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello */

#ifndef _Included_hello
#define _Included_hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello
 * Method:    print
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hello_print
  (JNIEnv *, jobject);

/*
 * Class:     hello
 * Method:    hello_open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hello_hello_1open
  (JNIEnv *, jobject);

/*
 * Class:     hello
 * Method:    hello_read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hello_hello_1read
  (JNIEnv *, jobject);

/*
 * Class:     hello
 * Method:    hello_write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hello_hello_1write
  (JNIEnv *, jobject, jint);

/*
 * Class:     hello
 * Method:    hello_ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hello_hello_1ioctl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
